// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.12.4
// source: proto/pwdm.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Login    string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthReq) Reset() {
	*x = AuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthReq) ProtoMessage() {}

func (x *AuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthReq.ProtoReflect.Descriptor instead.
func (*AuthReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{0}
}

func (x *AuthReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *AuthReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AuthResp) Reset() {
	*x = AuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResp) ProtoMessage() {}

func (x *AuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResp.ProtoReflect.Descriptor instead.
func (*AuthResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{1}
}

func (x *AuthResp) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type InsertLoginPasswordReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Login    string `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Tag      string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment  string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *InsertLoginPasswordReq) Reset() {
	*x = InsertLoginPasswordReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertLoginPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertLoginPasswordReq) ProtoMessage() {}

func (x *InsertLoginPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertLoginPasswordReq.ProtoReflect.Descriptor instead.
func (*InsertLoginPasswordReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{2}
}

func (x *InsertLoginPasswordReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InsertLoginPasswordReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertLoginPasswordReq) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *InsertLoginPasswordReq) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *InsertLoginPasswordReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InsertLoginPasswordReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type InsertCardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Num       string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Date      string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Cvc       string `protobuf:"bytes,5,opt,name=cvc,proto3" json:"cvc,omitempty"`
	FirstName string `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Tag       string `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment   string `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *InsertCardReq) Reset() {
	*x = InsertCardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertCardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertCardReq) ProtoMessage() {}

func (x *InsertCardReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertCardReq.ProtoReflect.Descriptor instead.
func (*InsertCardReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{3}
}

func (x *InsertCardReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InsertCardReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertCardReq) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *InsertCardReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *InsertCardReq) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

func (x *InsertCardReq) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *InsertCardReq) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *InsertCardReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InsertCardReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type InsertTextReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Tag     string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *InsertTextReq) Reset() {
	*x = InsertTextReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertTextReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTextReq) ProtoMessage() {}

func (x *InsertTextReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTextReq.ProtoReflect.Descriptor instead.
func (*InsertTextReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{4}
}

func (x *InsertTextReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InsertTextReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertTextReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *InsertTextReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InsertTextReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type InsertBinaryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    int32  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Tag     string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *InsertBinaryReq) Reset() {
	*x = InsertBinaryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertBinaryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertBinaryReq) ProtoMessage() {}

func (x *InsertBinaryReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertBinaryReq.ProtoReflect.Descriptor instead.
func (*InsertBinaryReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{5}
}

func (x *InsertBinaryReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *InsertBinaryReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertBinaryReq) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InsertBinaryReq) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *InsertBinaryReq) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type InsertResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *InsertResp) Reset() {
	*x = InsertResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InsertResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertResp) ProtoMessage() {}

func (x *InsertResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertResp.ProtoReflect.Descriptor instead.
func (*InsertResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{6}
}

func (x *InsertResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InsertResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetItemReq) Reset() {
	*x = GetItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemReq) ProtoMessage() {}

func (x *GetItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemReq.ProtoReflect.Descriptor instead.
func (*GetItemReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{7}
}

func (x *GetItemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetItemReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetLoginPasswordResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Login    string `protobuf:"bytes,3,opt,name=login,proto3" json:"login,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Tag      string `protobuf:"bytes,5,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment  string `protobuf:"bytes,6,opt,name=comment,proto3" json:"comment,omitempty"`
	Error    string `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetLoginPasswordResp) Reset() {
	*x = GetLoginPasswordResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLoginPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginPasswordResp) ProtoMessage() {}

func (x *GetLoginPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginPasswordResp.ProtoReflect.Descriptor instead.
func (*GetLoginPasswordResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{8}
}

func (x *GetLoginPasswordResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLoginPasswordResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetLoginPasswordResp) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *GetLoginPasswordResp) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *GetLoginPasswordResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetLoginPasswordResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetLoginPasswordResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetCardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title     string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Num       string `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	Date      string `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	Cvc       string `protobuf:"bytes,5,opt,name=cvc,proto3" json:"cvc,omitempty"`
	FirstName string `protobuf:"bytes,6,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName  string `protobuf:"bytes,7,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Tag       string `protobuf:"bytes,8,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment   string `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	Error     string `protobuf:"bytes,10,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetCardResp) Reset() {
	*x = GetCardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardResp) ProtoMessage() {}

func (x *GetCardResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardResp.ProtoReflect.Descriptor instead.
func (*GetCardResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{9}
}

func (x *GetCardResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetCardResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetCardResp) GetNum() string {
	if x != nil {
		return x.Num
	}
	return ""
}

func (x *GetCardResp) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetCardResp) GetCvc() string {
	if x != nil {
		return x.Cvc
	}
	return ""
}

func (x *GetCardResp) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *GetCardResp) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *GetCardResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetCardResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetCardResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTextResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Tag     string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Error   string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetTextResp) Reset() {
	*x = GetTextResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTextResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTextResp) ProtoMessage() {}

func (x *GetTextResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTextResp.ProtoReflect.Descriptor instead.
func (*GetTextResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{10}
}

func (x *GetTextResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetTextResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetTextResp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *GetTextResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetTextResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetTextResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetBinaryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Tag     string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
	Error   string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetBinaryResp) Reset() {
	*x = GetBinaryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBinaryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBinaryResp) ProtoMessage() {}

func (x *GetBinaryResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBinaryResp.ProtoReflect.Descriptor instead.
func (*GetBinaryResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{11}
}

func (x *GetBinaryResp) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetBinaryResp) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetBinaryResp) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetBinaryResp) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *GetBinaryResp) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *GetBinaryResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteItemReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type int32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DeleteItemReq) Reset() {
	*x = DeleteItemReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteItemReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemReq) ProtoMessage() {}

func (x *DeleteItemReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemReq.ProtoReflect.Descriptor instead.
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteItemReq) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteItemReq) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type DeleteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DeleteResp) Reset() {
	*x = DeleteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResp) ProtoMessage() {}

func (x *DeleteResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResp.ProtoReflect.Descriptor instead.
func (*DeleteResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{14}
}

type ShowItemsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ShowItemsResp_ItemModel `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Error string                     `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ShowItemsResp) Reset() {
	*x = ShowItemsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowItemsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowItemsResp) ProtoMessage() {}

func (x *ShowItemsResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowItemsResp.ProtoReflect.Descriptor instead.
func (*ShowItemsResp) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{15}
}

func (x *ShowItemsResp) GetItems() []*ShowItemsResp_ItemModel {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ShowItemsResp) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ShowItemsResp_ItemModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type    int32  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Tag     string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Comment string `protobuf:"bytes,5,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (x *ShowItemsResp_ItemModel) Reset() {
	*x = ShowItemsResp_ItemModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pwdm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShowItemsResp_ItemModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShowItemsResp_ItemModel) ProtoMessage() {}

func (x *ShowItemsResp_ItemModel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pwdm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShowItemsResp_ItemModel.ProtoReflect.Descriptor instead.
func (*ShowItemsResp_ItemModel) Descriptor() ([]byte, []int) {
	return file_proto_pwdm_proto_rawDescGZIP(), []int{15, 0}
}

func (x *ShowItemsResp_ItemModel) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShowItemsResp_ItemModel) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ShowItemsResp_ItemModel) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ShowItemsResp_ItemModel) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ShowItemsResp_ItemModel) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

var File_proto_pwdm_proto protoreflect.FileDescriptor

var file_proto_pwdm_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x70, 0x77, 0x64, 0x6d, 0x22, 0x3b, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x36, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xa0, 0x01,
	0x0a, 0x16, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0xd9, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x76, 0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74,
	0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x79, 0x0a, 0x0d,
	0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x7b, 0x0a, 0x0f, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x22, 0x48, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x30,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x22, 0xb0, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0xe9, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x76, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x76,
	0x63, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x61, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22,
	0x89, 0x01, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x0d,
	0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x33, 0x0a, 0x0d, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x22,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0xcd, 0x01, 0x0a, 0x0d,
	0x53, 0x68, 0x6f, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x33, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x2e, 0x49, 0x74, 0x65, 0x6d, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x71, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61,
	0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x5e, 0x0a, 0x0b, 0x41,
	0x75, 0x74, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x0d, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x26, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x65, 0x72, 0x12, 0x0d, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x0e, 0x2e, 0x70, 0x77,
	0x64, 0x6d, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x32, 0xb7, 0x03, 0x0a, 0x0f,
	0x47, 0x69, 0x76, 0x65, 0x54, 0x61, 0x6b, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x3b, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x4c, 0x6f, 0x67, 0x50, 0x77, 0x64, 0x12, 0x1c, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x77, 0x64,
	0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30, 0x0a, 0x07,
	0x49, 0x6e, 0x73, 0x43, 0x61, 0x72, 0x64, 0x12, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x49,
	0x6e, 0x73, 0x65, 0x72, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x30,
	0x0a, 0x07, 0x49, 0x6e, 0x73, 0x54, 0x65, 0x78, 0x74, 0x12, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x6d,
	0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x10,
	0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x34, 0x0a, 0x09, 0x49, 0x6e, 0x73, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x15, 0x2e,
	0x70, 0x77, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x49, 0x6e, 0x73, 0x65,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x67,
	0x50, 0x77, 0x64, 0x12, 0x10, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x12, 0x10, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x2e, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x10, 0x2e, 0x70,
	0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x11,
	0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x32, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72, 0x79, 0x12, 0x10,
	0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x65, 0x71,
	0x1a, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x32, 0x41, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x32, 0x3e, 0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x77,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0b, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x77, 0x64, 0x6d, 0x2e, 0x53, 0x68, 0x6f, 0x77, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pwdm_proto_rawDescOnce sync.Once
	file_proto_pwdm_proto_rawDescData = file_proto_pwdm_proto_rawDesc
)

func file_proto_pwdm_proto_rawDescGZIP() []byte {
	file_proto_pwdm_proto_rawDescOnce.Do(func() {
		file_proto_pwdm_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pwdm_proto_rawDescData)
	})
	return file_proto_pwdm_proto_rawDescData
}

var file_proto_pwdm_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_pwdm_proto_goTypes = []interface{}{
	(*AuthReq)(nil),                 // 0: pwdm.AuthReq
	(*AuthResp)(nil),                // 1: pwdm.AuthResp
	(*InsertLoginPasswordReq)(nil),  // 2: pwdm.InsertLoginPasswordReq
	(*InsertCardReq)(nil),           // 3: pwdm.InsertCardReq
	(*InsertTextReq)(nil),           // 4: pwdm.InsertTextReq
	(*InsertBinaryReq)(nil),         // 5: pwdm.InsertBinaryReq
	(*InsertResp)(nil),              // 6: pwdm.InsertResp
	(*GetItemReq)(nil),              // 7: pwdm.GetItemReq
	(*GetLoginPasswordResp)(nil),    // 8: pwdm.GetLoginPasswordResp
	(*GetCardResp)(nil),             // 9: pwdm.GetCardResp
	(*GetTextResp)(nil),             // 10: pwdm.GetTextResp
	(*GetBinaryResp)(nil),           // 11: pwdm.GetBinaryResp
	(*DeleteItemReq)(nil),           // 12: pwdm.DeleteItemReq
	(*DeleteResp)(nil),              // 13: pwdm.DeleteResp
	(*Empty)(nil),                   // 14: pwdm.Empty
	(*ShowItemsResp)(nil),           // 15: pwdm.ShowItemsResp
	(*ShowItemsResp_ItemModel)(nil), // 16: pwdm.ShowItemsResp.ItemModel
}
var file_proto_pwdm_proto_depIdxs = []int32{
	16, // 0: pwdm.ShowItemsResp.items:type_name -> pwdm.ShowItemsResp.ItemModel
	0,  // 1: pwdm.AuthService.Create:input_type -> pwdm.AuthReq
	0,  // 2: pwdm.AuthService.Enter:input_type -> pwdm.AuthReq
	2,  // 3: pwdm.GiveTakeService.InsLogPwd:input_type -> pwdm.InsertLoginPasswordReq
	3,  // 4: pwdm.GiveTakeService.InsCard:input_type -> pwdm.InsertCardReq
	4,  // 5: pwdm.GiveTakeService.InsText:input_type -> pwdm.InsertTextReq
	5,  // 6: pwdm.GiveTakeService.InsBinary:input_type -> pwdm.InsertBinaryReq
	7,  // 7: pwdm.GiveTakeService.GetLogPwd:input_type -> pwdm.GetItemReq
	7,  // 8: pwdm.GiveTakeService.GetCard:input_type -> pwdm.GetItemReq
	7,  // 9: pwdm.GiveTakeService.GetText:input_type -> pwdm.GetItemReq
	7,  // 10: pwdm.GiveTakeService.GetBinary:input_type -> pwdm.GetItemReq
	12, // 11: pwdm.DeleteService.DelItem:input_type -> pwdm.DeleteItemReq
	14, // 12: pwdm.ShowInfoService.GetInfo:input_type -> pwdm.Empty
	1,  // 13: pwdm.AuthService.Create:output_type -> pwdm.AuthResp
	1,  // 14: pwdm.AuthService.Enter:output_type -> pwdm.AuthResp
	6,  // 15: pwdm.GiveTakeService.InsLogPwd:output_type -> pwdm.InsertResp
	6,  // 16: pwdm.GiveTakeService.InsCard:output_type -> pwdm.InsertResp
	6,  // 17: pwdm.GiveTakeService.InsText:output_type -> pwdm.InsertResp
	6,  // 18: pwdm.GiveTakeService.InsBinary:output_type -> pwdm.InsertResp
	8,  // 19: pwdm.GiveTakeService.GetLogPwd:output_type -> pwdm.GetLoginPasswordResp
	9,  // 20: pwdm.GiveTakeService.GetCard:output_type -> pwdm.GetCardResp
	10, // 21: pwdm.GiveTakeService.GetText:output_type -> pwdm.GetTextResp
	11, // 22: pwdm.GiveTakeService.GetBinary:output_type -> pwdm.GetBinaryResp
	13, // 23: pwdm.DeleteService.DelItem:output_type -> pwdm.DeleteResp
	15, // 24: pwdm.ShowInfoService.GetInfo:output_type -> pwdm.ShowItemsResp
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_pwdm_proto_init() }
func file_proto_pwdm_proto_init() {
	if File_proto_pwdm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pwdm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertLoginPasswordReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertCardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertTextReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertBinaryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InsertResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLoginPasswordResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTextResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBinaryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteItemReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowItemsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pwdm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShowItemsResp_ItemModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pwdm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_pwdm_proto_goTypes,
		DependencyIndexes: file_proto_pwdm_proto_depIdxs,
		MessageInfos:      file_proto_pwdm_proto_msgTypes,
	}.Build()
	File_proto_pwdm_proto = out.File
	file_proto_pwdm_proto_rawDesc = nil
	file_proto_pwdm_proto_goTypes = nil
	file_proto_pwdm_proto_depIdxs = nil
}
